### ISSUE TITLE
Generated Feed Contains Newline Characters

### ISSUE THREAD

**Issue by TravisCrist** [yogthos/clj-rss#15]
When I go to make a feed using clj-rss I noticed that in order to make the feed pretty to print its adding a newline character to each item in the feed before and after the item. 

For my implementation this is not ideal so I would like to remove the newlines from the generated rss feed via some kind of property. Maybe a pretty print boolean could be setup so when added it adds the newlines and when not added they are not present. 

Steps to reproduce: 
 1. Use first example from https://github.com/yogthos/clj-rss 

    ```clojure
    (require '[clj-rss.core :as rss])

    (rss/channel-xml {:title "Foo" :link "http://foo/bar" :description "some channel"}
                     {:title "Foo"}
                     {:title "post" :author "author@foo.bar"}
                     {:description "bar"})
    ```  
 2.  Run in REPL, the output is: 

    ```xml
    <?xml` version='1.0' encoding='UTF-8'?>\n<rss version='2.0' xmlns:atom='http://www.w3.org/2005/Atom'>\n<channel>\n<atom:link href='http://foo/bar' rel='self' type='application/rss+xml'/>\n<title>\nFoo\n</title>\n<link>\nhttp://foo/bar\n</link>\n<description>\nsome channel\n</description>\n<generator>\nclj-rss\n</generator>\n<item>\n<title>\nFoo\n</title>\n</item>\n<item>\n<title>\npost\n</title>\n<author>\nauthor@foo.bar\n</author>\n</item>\n<item>\n<description>\nbar\n</description>\n</item>\n</channel>\n</rss>\n
    ```

Notice all the **\n** newline characters, ideally there would be a way to remove them. 

I forked the repo to see if I can figure this out but as I am new to clojure development I thought this might be something simple to fix which would save me some time on my current project. Alternatively if you have any tips on how to solve this I will gladly implement them and submit a pull request. Thanks for the assistance.

**Comment by yogthos** [comment]
Currently, the feed gets generated using the [clojure.xml/emit](https://clojuredocs.org/clojure.xml/emit) function, and it doesn't appear to provide a way to do non-formatted output. Looking at the source [here](https://github.com/clojure/data.xml/blob/c541be3517ecd5d0761847ac6bd585c92c5d34ed/src/main/clojure/clojure/data/xml/jvm/emit.clj), it looks like the Java XML writer ends up adding the newlines.

One option in your case might be to just strip them from the generated string.

**Comment by TravisCrist** [comment]
Thanks for the feedback and tips, I see what you mean about emit putting in the newlines. Not much you can really do about that, at least in clj-rss. I was thinking of just replacing them but thought there might have been a better way. I ended up just using a str/replace with the regex #"\n" to replace all the newlines with "". That seems to be working. Closing the issue since its not a problem with clj-rss it. Thanks for the assistance!

**Comment by yogthos** [comment]
No problem, and I think the regex is definitely the way to go here if you know you don't have any \n characters in the actual text.
